<?php
/*
 * This file is part of the Engine framework.
 * (c) Mathias Methner <mathiasmethner@gmail.com>
 * Please view the LICENSE file
 */
?>
<!DOCTYPE html>
<html>
<head>
    <title>Engine\Core Documentation</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="robots" content="index, follow, all"/>
    <meta name="Author" content="Mathias Methner"/>
    <meta name="Keywords"
          content="php, framework, mvc, engine, Mathias Methner"/>
    <?=$this->favicon('root::favicon.png');?>
    <?=$this->stylesheet('root::stylesheet.css');?>
    <?=$this->jsHead();?>
</head>
<body>
<?=$this->content();?>
<?=$this->jsFoot();?>
</body>
</html>