<?php
/*
 * This file is part of the Engine framework.
 * (c) Mathias Methner <mathiasmethner@gmail.com>
 * Please view the LICENSE file
 */
$this->extend('Base::skeleton-content.phtml');
?>
<h1>Documentation</h1>

<h1>Spot2</h1>

<h2>important links</h2>
<ul>
    <li><a
            href="http://phpdatamapper.com/docs/">Documentation</a></li>
    <li><a
            href="https://github.com/vlucas/spot2">Documentation &amp; Source Code</a></li>
    <li><a href="http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html">Doctrine DBAL
            Field Types</a></li>
    <li>
        <a href="http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/schema-representation.html">Doctrine
            Schema representation</a></li>

</ul>

<h1>Bootstrap / JQuery / CSS</h1>

<h2>important links</h2>
<ul>
    <li><a href="http://eternicode.github.io/bootstrap-datepicker">Bootstrap
            Datepicker</a></li>
</ul>
